### ISSUE TITLE
Profile inputs doesn't pickup the type of profile properly.

### ISSUE THREAD

**Issue by m-s-abeer** [Yankee-16/Resume-Builder#2]
Please checkout below pictures:
[Input Section](https://ibb.co/2ZGVb0m)
[Pdf Section](https://ibb.co/t2hTPFd)

The linkedIn profile got into twitter.

**Comment by smhimran** [comment]
Thanks for the issue. It was a typo in the redux store where it gets data from localstorage. Now it is fixed, please check it out
